### ISSUE TITLE
Release new gem version

### ISSUE THREAD

**Issue by ifourmanov** [sensu-plugins/sensu-plugins-puppet#13]
Can you please release new gem version? So that we could have check puppet failures functionality brought by https://github.com/sensu-plugins/sensu-plugins-puppet/commit/af83da7e69e908d2332efb40795d0373c9286e95 and https://github.com/sensu-plugins/sensu-plugins-puppet/commit/b9dda10d637d97186d33ea13c4d49c1c1f55e635

**Comment by eheydrick** [comment]
1.1.0 is live on rubygems.
