### ISSUE TITLE
check-puppet-last-run crash with -i option

### ISSUE THREAD

**Issue by bovy89** [sensu-plugins/sensu-plugins-puppet#20]
Check-puppet-last-run.rb with -i option is not working

Check failed to run: undefined method `>' for nil:NilClass, ["/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-puppet-2.1.0/bin/check-puppet-last-run.rb:138:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]

**Comment by bovy89** [comment]
PR #21 created

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-puppet/versions/2.1.1
