### ISSUE TITLE
Sensu user lacking permissions to read /opt/puppetlabs/puppet/cache/state/last_run_summary.yaml

### ISSUE THREAD

**Issue by dalesit** [sensu-plugins/sensu-plugins-puppet#3]
In my instance (running puppet 4) the sensu user doesn't have permissions to read `/opt/puppetlabs/puppet/cache/state/last_run_summary.yaml` so the check fails.

I worked around this by creating a `sudoers.d` entry for sensu, and changing the sensu check command to call `check-puppet-last-run.rb` using `sudo`.

**Comment by eheydrick** [comment]
Thanks for catching that. I think we should add a note to the usage about needing to run with sudo. Can you open a PR.

**Comment by dalesit** [comment]
PR #4 created...

**Comment by eheydrick** [comment]
Thanks for the PR!
