### ISSUE TITLE
Path to `last_run_summary.yaml` has changed in Puppet 7

### ISSUE THREAD

**Issue by Debilski** [sensu-plugins/sensu-plugins-puppet#40]
$ puppet config print all | grep last
    lastrunfile = /opt/puppetlabs/puppet/public/last_run_summary.yaml
    lastrunreport = /opt/puppetlabs/puppet/cache/state/last_run_report.yaml

**Comment by jspaleta** [comment]
It's not just the the location.. the file structure has changed significantly as well.
